## 什么是异常

 *异常是在程序执行期间*发生*的事件，它破坏了程序指令的正常流程*

- 程序运行产生错误时，会创建一个异常对象(包含程序的错误信息)并将该对象交给运行时系统，该过程称为**抛出异常**
- 运行时系统会从错误开始处搜索异常的处理程序，如果找到即交给相应的程序进行处理，次过程称为**捕获异常**否则终止程序

- 异常可分为三类，已检查异常，错误，运行时异常，错误(不能手动处理)和运行时异常统称为未检查异常
- 已检查异常是编译器会自动提示需要使用try-catch语句进行处理，未检查异常则不会提示比如RuntimeException与其子类异常，但是Error不可手动处理

## 异常的捕获与处理

```java
try { 
	//可以抛出异常的语句
} catch (IndexOutOfBoundsException e) { 
    System.err.println("IndexOutOfBoundsException: " + e.getMessage()); 
} catch (IOException e) { 
    System.err.println("Caught IOException: " + e.getMessage()); 
}
```

以上代码是异常的基本捕获语句，上面的catch语句捕获的异常必须是下面的捕获异常的子类，否则编译器会报错

```java
try { 
	//可以抛出异常的语句
} catch (IndexOutOfBoundsException e) { 
    System.err.println("IndexOutOfBoundsException: " + e.getMessage()); 
} catch (IOException e) { 
    System.err.println("Caught IOException: " + e.getMessage()); 
}finally{
    //一定会被执行的语句
}
```

finally语句保证了异常处理的一些后续的必要处理比如关闭一些必须关闭的资源，即使在catch语句中意外return,finally语句也依然会被执行，java 7 之后引入了`try-`with-resources为了更好的关闭资源

```java
public void writeList() throws IOException, IndexOutOfBoundsException...{}
```

如果不想在方法内部处理异常，可以将异常抛出在外部创建一个统一处理的异常类

## 创建异常类

首先我们看图了解一下异常类的派生关系，Error不被处理，RuntimeException异常通常指示API调用错误，一个典型的示例就是 NullPointerException

![](D:\mysoft_install\Typora\notes\again\java\img\05.png)

你可以在选择继承合适的Exception类，进行定义自己的异常类

### 链式异常

如果你捕获到了一个异常，你可以先不进行处理而是向外抛出一个附带该错误信息的更高级别的异常,注意throw与throws的使用场景

```java
try { 

} catch (IOException e) { 
    throw new SampleException("Other IOException", e); 
}
```